ikalchev/HAP-python

.gitignore
pyhap/accessories/TSL2591.py

+ added tsl2591 - Light Sensor

---

main.py
pyhap/accessory.py
pyhap/accessory_driver.py
setup.py

For Issue #24 
Needs further discussion, such as how to make the bitwise ops more dynamic. 
My lack of proper Apple Documentation limits this for me. :)

Issue #24 - Initial X-HM:// URI and QR Setup Code work

---

.coveragerc
.gitignore
.travis.yml
codecov.yml
docs/source/api.rst
docs/source/intro/examples.rst
docs/source/intro/install.rst
docs/source/intro/overview.rst
docs/source/intro/tutorial.rst
tests/__init__.py
tests/requirements.txt
tox.ini

Here is everything you'll need for Travis-CI.
You'll want to take a look at the `deploy` section on `.travis.yml`
This is setup to handle automatic deployments from `master` to pypi. Also setup to handle `RC` and `dev` branches.
See here for a successful build for my `master` branch.
https://travis-ci.org/jslay88/HAP-python/builds/343249726

Travis-CI Setup and Codecov Coverage Reports

---

.gitignore
pyhap/accessory.py
pyhap/characteristic.py
pyhap/service.py

For `Accessory`, `Service` and `Characteristic`  
Added python venv suff to `.gitignore`.

Added object representations

---

README.md
requirements_all.txt

Makes it easier for users to install all needed dependencies.

Added requirements file

---

pyhap/accessory_driver.py

The current event loop implementation produces an error when `HAP-python` isn't run in the main thread.
- `get_event_loop()` should be changed with `new_event_loop()`
- I've added `event_loop.stop()` for the `accessory_driver.stop()` method
- As a suggestion I personally would use `event_loop.run_forever()` in combination with `try / finally` instead of `event_loop.run_until_complete()`. At the moment this might not be necessary, but it will in the future when all events from HomeKit are send to the event loop. It also is a bit more resilient towards errors and in theory we shouldn't need the `signal_handler` method to stop the event_loop with a KeyboardInterrupt.

Event loop Fix

---

CHANGELOG.md
pyhap/characteristic.py
tests/test_characteristic.py
tests/test_service.py

Split of from #92. Merge order: 1
- Log output for `char.set_value` and `char.client_update_value` to make debugging a bit easier
- Rewrote `test_characteristic`
- None

Improvements 1 - Characteristic

---

CHANGELOG.md
pyhap/accessory.py
pyhap/iid_manager.py
tests/test_iid_manager.py

Split of from #92. Merge order: 2
- Moved `IIDManager` to separate file
- Rewrote `IIDManager`
- Split `remove` into `remove_obj` and `remove_iid`
- Added tests
- None

Improvements 2 - IID Manager

---

CHANGELOG.md
README.md
pyhap/__init__.py
pyhap/accessory.py
requirements.txt
setup.py

Split of from #92.
- `pip install HAP-python[QRCode]` now installs all dependencies inclusive those to display the QR-Code during setup.
- QR Code is now optional

Improvements 5 - QR Code

---

README.md

`util` is not used in the code snippet

Unused import in README.md

---

accessories/NeoPixelLightStrip.py

Updated incorrect python formatting as requested.
Removed commented functions that were not used.
Updated constructor definition to take same parameters as NeoPixel Library (rpi_ws281x).

NeoPixels Update

---

CHANGELOG.md
pyhap/accessory_driver.py

Fix spelling executor

---

pyhap/hap_server.py

I have been using HAP-python with home assistant on a Raspberry Zero W. My homekit will randomly goes into "No Response" status and also randomly recover on itself. After some debugging it looks like the socket sometimes will throw exception with `errno.EBADF`, at this point HAP-python will also throw and my homekit will immediately goes into "No Response" until next `pair-verify` initiated by homekit hub.
I don't exactly know in which case the `EBADF` exception will happen, but my guess is that Raspberry ZW only have 2.4GHz wifi, and my area's band is very crowded, so maybe when there's interference the `EBADF` will be the error number.
After applied this change locally, I has been running without "No Response" for about two weeks.

Also consider EBADF to be a timeout. Add some logging.

---

README.md

Docs for https://github.com/ikalchev/HAP-python/pull/229

Service callbacks example

---

pyhap/camera.py

These are changes required for integrating camera support into Home Assistant core. See home-assistant/core#32527

Home assistant camera

---

pyhap/accessory_driver.py
tests/test_accessory_driver.py

Asking siri to turn off all the light or on all the lights sends multiple aids.  Service callbacks need to support this in order for it to work.  Sorry I missed this on the first go.
https://github.com/home-assistant/core/issues/33764

Make service callbacks handle multiple aids

---

pyhap/accessory_driver.py

This should fix https://github.com/ikalchev/HAP-python/issues/160 once I add a config option to Home Assistant

Add option to select Zeroconf broadcast

---

.travis.yml
pyhap/accessory.py
pyhap/accessory_driver.py
pyhap/hap_server.py
pyhap/hsrp.py
pyhap/tlv.py
pyhap/util.py
tests/conftest.py
tests/test_accessory_driver.py
tests/test_camera.py
tests/test_hap_server.py
tests/test_hap_socket.py

This is a work in progress and will conflict with https://github.com/ikalchev/HAP-python/pull/252 so I'll rework it after that

Various code cleanups, add py37/38 to travis

---

camera_main.py

The camera demo should now work out of the box

Auto-detect IP address

---

pyhap/hap_server.py

Fixes #230
Leaving this as a draft as I want to run it for a few days.

Handle a single byte read request in encrypted data stream

---

pyhap/hap_server.py

Improve spec compliance when an error occurs.

Ensure an error response is generated on exception

---

pyhap/accessory_driver.py
tests/test_accessory_driver.py

Prevents unexpected zeroconf exception

Filter invalid characters from accessory friendly names

---

pyhap/hap_handler.py
tests/test_hap_handler.py

Noticed this when I accidentally set the port wrong for a test bridge and homekit couldn't provide a useful error message

Send unavailable tlv when attempting pairing and already paired

---

pyhap/loader.py

These methods have been deprecated for a long time
and are no longer used.

Remove deprecated get_char_loader and get_serv_loader

---

pyhap/accessory.py
tests/__init__.py
tests/test_accessory.py

- Remove deprecated accessory _set_services and config_changed functions
- Increase accessory test coverage

Fix accessory run not being awaited from a bridge

---

pyhap/tlv.py
tests/test_tlv.py

Complete coverage for tlv

---

pyhap/hap_server.py
tests/test_hap_server.py
tests/test_hsrp.py

Complete coverage for hap_server

---

pyhap/accessory.py
tests/test_accessory.py
tests/test_accessory_driver.py
tests/test_hap_server.py
tests/test_tlv.py

Fix run_at_interval with multiple accessories

---

pyhap/encoder.py
pyhap/hap_handler.py
pyhap/state.py
requirements.txt
requirements_all.txt
setup.py
tests/test_accessory_driver.py
tests/test_encoder.py
tests/test_state.py

- Drop curve25519-donna as its unmaintained
Requires https://github.com/ikalchev/HAP-python/pull/355

Switch to using cryptography x25519

---

pyhap/characteristic.py
tests/test_characteristic.py

- The fix in #378 did not work as expected due to
a floating point accuracy problem

Fix floating point values with minStep

---

pyhap/characteristic.py

Switch to use an intersection since its faster

Speed up get accessories

---

pyhap/accessory_driver.py
pyhap/hap_handler.py
tests/test_hap_handler.py

UUIDs must be upper case with iOS 16 or they will get unpaired by the iOS device because it no longer compares them case insensitive.

Fix pairing with iOS 16

---

pyhap/accessory.py
pyhap/camera.py
pyhap/hap_handler.py
pyhap/hsrp.py
pyhap/util.py
setup.py

async_timeout does not suffer from the same race
problems as asyncio.wait_for
see https://github.com/python/cpython/pull/98518
for more details

Switch timeouts to use async_timeout

---

pyhap/accessory_driver.py
pyhap/hap_protocol.py
pyhap/util.py

https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:

Ensure tasks are not garbage collected before they finish

---

pyhap/accessory.py
pyproject.toml

CI should pass with the combination of this PR and https://github.com/ikalchev/HAP-python/pull/478

Fix pylint complaints
