pyhap/resources/characteristics.json
I noticed that the min value for `CurrentTemperature` was set to `0` which doesn't account for negative temperatures.
I really like your project. After I saw the discussion in the `HomeAssistant` Forum about implementing `Homekit` support, I tried a few things with your project myself 👍
=> Bugfix: Changed CurrentTemperature min/max values

main.py, pyhap/accessory.py, pyhap/util.py, tox.ini
Generate random `pincode` and `setup_id` each time the process is restarted (unless explicitly passed in).
This is in line with the recommendations from the Apple HAP documentation: https://developer.apple.com/support/homekit-accessory-protocol/
=> Dynamic codes

pyhap/characteristic.py, tests/test_characteristic.py
Related discussion: #26
* Removed `_create_hap_template` an merged this into `to_HAP`
* New method `override_properties` for chars
* Removed `self.has_valid_values` and replaced it with runtime checks to prevent update errors
=> Char: override_properties

pyhap/accessory_driver.py
I recently came across an issue on the Home Assistant Github page: https://github.com/home-assistant/home-assistant/issues/13345
A user has two iPads and if he executes a command on one the state doesn't change on the second one. I believe that can be fixed with setting `should_notify=True` in the `set_characteristics` method of `accessory_driver`. However I don't know if there are any reasons why you choose to set it in the first place.
=> Acc Driver: Should_notify

pyhap/characteristic.py
A `valid_value` set to 0 makes testing easier. Before the `next` function could return any of the values, since (at least for py35) `dict.values` doesn't necessarily returns a sorted list.
The value `0` is set for all characteristics that have the attribute `validValues` so it shouldn't be an issue.
=> Char: Set default for 'valid_value' to 0

pyhap/accessories/FakeFan.py, pyhap/accessories/Http.py, pyhap/accessories/SDS011.py, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/service.py, tests/test_service.py
A bit cleanup.
Removed:
* opt_characteristics (service)
* add_opt_characteristics (service)
* get_value (chars)
* Removed `add_opt_characteristic`. There is no further distinction between optional and require chars during execution. All chars that have been added as `optional` should now simply use `add_characteristic`. (The loader hasn't changed.)
* The method `get_characteristic` now raises a `ValueError` if the characteristic isn't found
* The already deprecated method `get_value` was removed. Use `char.value` instead.
=> Remove opt_chars and get_value

.gitignore, pyhap/accessories/SDS011.py, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/service.py, tests/test_characteristic.py
I started working on `characteristic.py` and got some first results.
Thats what I have planed:
This should lead to:
- Add the classmethod `from_dict` --> later
- Change loader to use `from_dict` --> later
- `set_value` doesn't take `should_callback` anymore
=> Characteristic improvements

pyhap/characteristic.py
If properties are overridden, we should make sure that we still have a valid value. If not, getting a new default value seems to be a good idea, since `overriding` usually happens in the `__init__` call for an accessory.
=> Fix for overriding properties

README.md, main.py, pyhap/accessories/TemperatureSensor.py, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/util.py, tests/test_accessory_driver.py, tox.ini
Problems to solve:
- Support non-coroutine run methods - not all code could switch to
asyncio, these should be started in a thread as before.
- Port accessories/*
=> [WIP] Move to coroutines for Accessory.run

.travis.yml
Async syntax is first supported in py3.5
=> Travis - Removed py34

docs/source/api/characteristic.rst, docs/source/api/loader.rst, docs/source/api/service.rst, pyhap/accessory.py, pyhap/characteristic.py, pyhap/service.py, tests/requirements.txt, tests/test_accessory.py, tests/test_characteristic.py, tests/test_loader.py, tests/test_service.py, tox.ini
Except for two tests in `accessory_driver` everything else should pass now. While I was updating the tests I found some bugs that are now fixed. Since the two failing tests block travis, I added `pytest-timeout` to the test dependencies and set `timeout=3`.
Changelog:
* Fixed Service.configure_char method
* Fixed Accessory._set_service
* Fixed Characteristic.override_properties
* Fixed docs
* New tests
* Added pytest-timeout
=> Updated tests, bugfixes

pyhap/accessories/AM2302.py, pyhap/accessories/BMP180.py, pyhap/accessories/DisplaySwitch.py, pyhap/accessories/FakeFan.py, pyhap/accessories/Http.py, pyhap/accessories/LightBulb.py, pyhap/accessories/MotionSensor.py, pyhap/accessories/SDS011.py, pyhap/accessories/ShutdownSwitch.py, pyhap/accessories/TSL2591.py, pyhap/accessories/TemperatureSensor.py
This PR should fix the accessory files. It requires #88 to fix them completely.
=> Fixed accessories

pyhap/accessory_driver.py, tests/test_accessory_driver.py
In addition to #83, `asyncio.Event()` needs to be called with the `loop` parameter. Otherwise it throws an error when not executed in the main thread.
=> Fix aio_stop_event

CHANGELOG.md
In response to: https://github.com/ikalchev/HAP-python/pull/89#issuecomment-381844882
There might still be some parts missing and I've only included the changes since `1.1.8`, but it`s a start.
=> Added initial Changelog

CHANGELOG.md, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/encoder.py
Split of from #92.
- Replaced double `"` for parameter values with `'`.
- Removed `object` inheritance
- Removed class from super calls if obvious
- Changed `Accessory.broker` to `Accessory.driver`. Also `acc.set_broker` is now `acc.set_driver`.
---
Also the change to `driver` might not be entirely necessary, it simplifies things with the better name.
=> Improvements 6 - Changes, Driver

CHANGELOG.md, main.py, pyhap/accessories/AM2302.py, pyhap/accessories/BMP180.py, pyhap/accessories/DisplaySwitch.py, pyhap/accessories/FakeFan.py, pyhap/accessories/Http.py, pyhap/accessories/LightBulb.py, pyhap/accessories/MotionSensor.py, pyhap/accessories/SDS011.py, pyhap/accessories/ShutdownSwitch.py, pyhap/accessories/TSL2591.py, pyhap/accessories/TemperatureSensor.py, pyhap/accessory.py
Split of from #92.
- Added helper method to enable easy override of the `AccessoryInformation` service.
- Added helper method to load a service and chars and add it to an accessory.
- The `AccessoryInformation` service will always have the `iid=1`.
- Updated accessories to account for changes
- Changed default values associated with the `AccessoryInformation` service.
- Removed accessory call to `Accessory._set_services`. Overriding this method not longer works. Instead services should be initialized in the accessories `init` method.
=> Improvements 4 - Service Helper

CHANGELOG.md, pyhap/__init__.py, setup.py
I'm not sure which version you want to go to, but I assumed from the deprecated notes that it should be `2.0.0`.
It would be really great if you could do the release soon. I could help by creating the merge PR once this (and maybe #107) is/are merged.
=> Version bump

README.md
=> Documentation improvements for version 2.0.0

CHANGELOG.md, pyhap/accessory.py, pyhap/accessory_driver.py
- Removed unused method `accessory.create`.
- Removed `iid_manager` and `setup_id` parameter from `accessory` and `bridge` `init` calls.
- Improved `accessory.to_HAP()`
In theory this is a breaking change. However it's not very likely many people have used those parameters to begin with since the defaults are quite fine. Therefor this shouldn't be an issue.
Some changes are extracted from #104. I didn't wanted to just propose a single new line ;)
In addition this will help keep the other PR clean.
=> Small changes - Accessory

pyhap/accessory.py
This typo was limited to the **`dev`** branch. No need to update **`master`**.
=> Fix typo in bridge.to_HAP

CHANGELOG.md, accessories/AM2302.py, accessories/BMP180.py, accessories/DisplaySwitch.py, accessories/SDS011.py, accessories/TSL2591.py, main.py, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/loader.py, pyhap/service.py, pylintrc, tests/conftest.py, tests/test_accessory.py, tests/test_accessory_driver.py, tests/test_encoder.py, tests/test_loader.py, tox.ini
During my improvement PR's I noticed that we assign may things to each accessory although they are only needed once (at the driver level). Especially for bridged accessories that is mostly unnecessary. This PR should be a first step in reversing this behavior.
Instead of assigning the accessory to the driver, I think that I would make much more sense to assign the driver to each accessory and later add the top level one to the driver.
**Note**: All these changes assume that we stick to the current version, where one driver only handles one top level accessory.
@ikalchev What do you think this?
=> Improvements 6 - Driver assignment

.gitignore, AUTHORS, CHANGELOG.md, LICENSE, docs/source/conf.py, pyhap/__init__.py, pyhap/const.py, requirements_test.txt, scripts/release, scripts/setup, setup.cfg, setup.py, tox.ini
Some suggestion on for the overall structure of the `HAP-python` project. The original intend was to add a section to the `LICENSE` file giving credit to other open source projects when code was adopted.
Next I wanted to include the `LICENSE` file in the distribution and I ended out moving almost all static content to `setup.cfg`.
In addition to small style changes (4-space indent for `tox.ini` for better readability), I also added two scripts to simplify setup and release. The later now generates a build distribution as well, not just a source distro.
For `setup`, I modified some files. The `description-file` wasn't included at all, so I removed it (also not really necessary IMO). If you think otherwise, the `long_description` attribute should work. Furthermore I added `keywords` and …
=> Changes to organization files

CHANGELOG.md, pyhap/const.py, setup.cfg
It seems like the `package_data` didn't get included in the wheel `HAP_python-2.2.0-py3-none-any.whl`. It worked for me with the `setuptools==39.2.0` which is why I probably didn't noticed it.
This should fix the issue, since `include_package_data` includes all none `.py` files in the package (`pyhap`) as long as it's specified in the `MANIFEST.in` which is the case.
=> Fix package_data, bump version to 2.2.1

CHANGELOG.md, pyhap/const.py, scripts/release, setup.cfg
Unfortunately I had wrote `date` instead of `data`, which resulted in the wheel being broken again :disappointed:
The upside is that it should work now, which I could test, since I just found out that I had to delete the build directory before I start a new one.
=> Fix spelling error, bump version to 2.2.2

accessories/NeoPixelLightStrip.py
Added ability to interface with NeoPixels RGB LEDs. This will allow changing of Color, Brightness and State(On/Off) of the NeoPixels attached to the RPi.
This accessory uses all available HomeKit Lightbulb API services (Hue, Saturation, Brightness).
This commit requires the installation of rpi_ws281x library. The procedure is outlined in # https://learn.adafruit.com/neopixels-on-raspberry-pi/software.
=> NeoPixelsLightStrip

pyhap/accessory_driver.py, pyhap/hap_server.py
The accessory should respond either with 204 (NO_CONTENT) or
with 207 and json with a specific status code. This change
returns 204 for all characteristics.
=> Fix set_characteristic #140

CHANGELOG.md, pyhap/characteristic.py, tests/test_characteristic.py
`HomeKit` automations initiate calls to the server without taking the current value into account. That isn't the case normally and even scenes respect them. I think the best option would be to integrate a check in `client_update_value` if the value is already set and if so ignore that call.
See also: https://github.com/home-assistant/home-assistant/pull/17453
CC: @adrum
=> Char - ignore duplicate values

CHANGELOG.md, pyhap/accessory_driver.py
In some cases the pairing doesn't work, because unregister and register of the mDNS service doesn't work as expected. If we remove the call to `update_advertisement` inside the `pair` and `unpair` methods, we eliminate that point of failure. The only drawback is that the user would either need to restart HAP-python after unpairing (that's want I would propose) or the service would need to be discoverable constantly.
Related issues:
https://github.com/home-assistant/home-assistant/issues/17181
https://github.com/home-assistant/home-assistant/issues/14567
=> Temp disable 'update_advertisment' after pairing

pyhap/accessory_driver.py
I would like to make it possible to advertise custom service IP addresses.
This is a requirement for the following use cases: 
- Running HAP (or Home Assistant) behind a NAT, e.g. with Docker.
- Running it on a system with multiple interfaces there the IP and hostname diverge.
The forwarding of the required mDNS packets can be done with an avahi-daemon based gateway, e.g. by using `enable-reflector=yes`.
=> Make it possible to advertise custom service IP and MAC address

pyhap/hap_server.py, tests/test_hap_server.py
Homekit needs the headers and content sent
in a single write call or it will randomly
get connection reset by peer which leads
to iOS stalling and devices showing up
as non-responsive.
Without HTTP/1.1 keep-alives, 50+ devices
would cause a bridge to timeout or devices
to go non-responsive because homekit would
have to make a new connection to get / put
for each device.  With HTTP/1.1 it can avoid
all of this overhead
After this change, devices in homekit on
the bridges with > 80 devices were
now immediately responsive in testing.
=> Add support for HTTP/1.1 and random non-responsive devices #197

pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, tests/conftest.py, tests/test_accessory_driver.py, tests/test_characteristic.py
Clients that made the characteristic change are NOT supposed to get
events
about the characteristic change as it can cause an unexpected HTTP
disconnect (connection
reset by peer) which leads temporary unresponsive accessories and
violates the HAP spec
=> Ensure events are not sent to the initiator client

pyhap/hap_server.py, requirements.txt, requirements_all.txt, setup.py
=> Switch to cryptography to resolve performance concerns.

pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/service.py, tests/test_accessory_driver.py
For some services we want to send all the char value
changes at once.  This resolves an issue where we send
ON and then BRIGHTNESS and the light would go to 100%
and then dim to the brightness because each callback
would only send one char at a time. 
For additional details about why this is needed:
https://github.com/home-assistant/core/pull/32348
https://github.com/home-assistant/core/issues/13695
https://github.com/home-assistant/core/issues/13768
https://github.com/home-assistant/core/issues/32278
The end result is that home assistant can now get sets for a service in one call and do the right thing
```
2020-03-19 02:14:28 DEBUG (Thread-48) [custom_components.homekit.type_lights] _set_chars: {'Brightness': 45}
2020-03-19 02:14:29 DEBUG (Thread-48) …
```
=> Add support for service callbacks

pyhap/hap_server.py
Handle short read in crypto stream
*  This implements the TODO to handle the short read.
*  recv_into should be a bit more efficient as well.
=> Avoid disconnect on short read

pyhap/hap_server.py
If a request fails with an exception other the socket timeout there
is no information of why, so add debug logging.
To give some background for this change I by accident built the cryptography package against a openssl fork that doesn't support ChaCha20Poly1305, which meant that my home-assistant server just closed all connections when getting requests from my phone without any information in the logs on why.
=> Add logging of exceptions in finish_request

pyhap/camera.py, tests/test_accessory_driver.py
* Fix exception on missing video fields
Takes care of the `# TODO: Optionals, handle the case where they are missing`.  Sometimes streams would fail to start because a field would be missing in `VIDEO_TYPES['ATTRIBUTES']`.  Everything is starting consistently now with this change.
* Make logging consistent
Logging was calling `logging` instead of `logger` like the other modules.  This meant the debug log didn't show up in Home Asssistant.
=> Fix exception on missing video fields

pyhap/accessory_driver.py, pyhap/hap_server.py
The mDNS announcement must not be updated until AFTER
the final pairing response is sent or homekit will
see that the accessory is already paired and assume
it should stop pairing as it assumes it lost the
race and another controller has paired.
This probably means safe mode can go away but I'm
not 100% sure on that.
=> Fix race condition that causes pairing and unpairing failures

pyhap/hap_server.py
I've been trying to catch this happening for a few months and finally
managed to catch it happening.
Pyhap loop
```
31.00%  31.00%    5.80s     5.80s   recv (pyhap/hap_server.py:763)
34.00%  34.00%    1.34s     1.36s   run (zeroconf/__init__.py:1223)
4.00%   4.00%    1.27s     1.27s   recv (pyhap/hap_server.py:766)
1.00%   1.00%   0.660s    0.660s   _worker (concurrent/futures/thread.py:78)
4.00%   4.00%   0.590s    0.590s   recv (pyhap/hap_server.py:769)
0.00%   0.00%   0.510s    0.510s   recv (pyhap/hap_server.py:768)
0.00%   0.00%   0.470s    0.470s   recv (pyhap/hap_server.py:749)
2.00%   2.00%   0.460s    0.460s   recv (pyhap/hap_server.py:762)
1.00%   1.00%   0.430s    0.430s   recv (pyhap/hap_server.py:765)
3.00%   3.00%   0.340s    0.340s   recv (pyhap/hap_server.py:767)
1.00% …
```
=> Fix loop on dropped connection

pyhap/accessory_driver.py, tests/test_accessory_driver.py
Home Assistant is now sharing a single `Zeroconf` instance between integrations to avoid the overhead of running multiple instances.  In some cases more than 10 instances were running at a time.
As each instance is listening for updates on the network the overhead can be significant, by sharing a singe instance this problem is mitigated.
=> Allow passing in a zeroconf instance.

pyhap/hap_server.py, tests/test_hap_server.py
After server restarts accessories would sometimes go
unavailable because after reconnecting and switching
to encrypted transport part of the unencrypted response
would not have been sent down the wire.  After the
upgrade to encrypted happens that response gets lost
which means the server starts sending encrypted data
when the hap client/controller is still expecting
to finish reading the unencrypted data.
The net result is that the controller/client has to
try again to get another connection to the server
where it does not get unluckly and hit this race
condition.
Before the change "Cleaning connection" was
very common in the log.  Its now rare.
Now that Apple has published more information,
we can improve conformance to HAP spec.
Content-Length is no longer sent on empty content
as it …
=> Fix random disconnect after upgrade to encrypted

pyhap/hap_server.py
The "Add logging of exceptions in finish_request" PR caused the exception to be suppressed instead of only adding logging.
=> Ensure exception is still thrown in finish_request

pyhap/characteristic.py
I've been working on making sure everything works with a RPi and a large number of accessories.  As part of of that I've been looking at performance bottlenecks.
I noticed that this was ~25% of the execution time when calling `get_accessories`.
=> Only stringify the characteristic uuid once

pyhap/accessory.py, pyhap/accessory_driver.py, tests/test_accessory_driver.py
Implements #194 
Example usage
https://github.com/bdraco/home-assistant/commit/a37b1fb0c4839f496aeea665d7f575ec66f9587c
Adds an exception guard to prevent the encrypted connection from being dropped and causing homekit to stall usually caused by the `getter_callback` throwing an unexpected exception.
=> Add support for accessory unavailability

pyhap/hap_server.py
I missed removing a `, False)` in the original PR. 🙈
=> Fix pairing after py37/py38 cleanup

pyhap/hap_server.py, tests/test_hap_server.py
#253 only fixed the write side of the issue.
Once the final response is sent data, can come
back over the wire before the reader is swapped
out to the encrypted reader.  This causes us to
loose the data and result in a disconnect.
Should solve #257
=> Split read/write encryption upgrade

pyhap/camera.py
Without this argument, avfoundation always generates the same frame rate, no matter what rate is negotiated by homekit (on my mac, this results in about 10fps)
=> "-framerate" is required to control avfoundation

pyhap/accessory_driver.py
=> Fix compatibility with zeroconf 0.27

pyhap/accessory_driver.py
This improves loop handling for HAP-Python:
- Do not change the default executor of passed in loops
- Do not shut down loops/executor pools that were passed in
=> Improve loop handling

pyhap/camera.py, tests/test_camera.py
Setting `stream_count` to a value above 1 will create multiple `CameraRTPStreamManagement` services.
This should be backwards compatible.
=> Add support for multiple camera streams

pyhap/accessory.py, pyhap/accessory_driver.py
I was running into an issue trying to deploy the same code for an accessory on two different RPis implemented with this library, with different hostnames. As soon as the second one was on, neither accessory would work anymore, they were both getting some corrupted/bad requests. They both had the same display_name, so I changed one and suddenly everything was working correctly. But this was weird, as I thought the autodiscovery features should account for this. That led me to this SO answer: https://stackoverflow.com/a/53867271/375530
Comparing what other HomeKit accessories do, it seems they append some parts of their MAC address to the mDNS name, giving some uniqueness if there are multiple bridges on the same network, for instance. Since the accessory I wrote has multiple physical …
=> ✨ Support multiple accessories with same name

pyhap/accessory_driver.py
`SimpleQueue` avoids a lot of the overhead of `Queue`.  Since the current implementation doesn't do anything advanced with the queue, we can benefit from the increased performance
=> Use SimpleQueue when available (python 3.7 and later)

pyhap/accessory.py
Add flush to print calls to make sure the accessory setup code appears in the log
when running under systemd
=> Add flush to print calls to make sure the accessory setup code is shown

pyhap/accessory_driver.py
Fixes
```
AttributeError: 'NoneType' object has no attribute 'available'
2020-10-29 11:20:44 ERROR (Thread-27) [pyhap.accessory_driver] Unexpected error getting value for characteristic <built-in function id>.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyhap/accessory_driver.py", line 673, in get_characteristics
available = acc.available
```
Reported here: https://github.com/home-assistant/core/issues/42157#issuecomment-719064388
=> Fix thread safety in get_characteristics

pyhap/hap_server.py
Looks like https://github.com/ikalchev/HAP-python/issues/230 is still happening:
```
Traceback (most recent call last):
File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 650, in process_request_thread
self.finish_request(request, client_address)
File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 943, in finish_request
self.RequestHandlerClass(request, client_address,
File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
super(HAPServerHandler, self).__init__(sock, client_addr, server)
File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 720, in __init__
self.handle()
File …
```
=> Handle request for an empty read instead of throwing an exception

.github/workflows/ci.yaml, pyhap/accessory.py, pyhap/camera.py, pyproject.toml, requirements_test.txt, tests/test_accessory.py, tox.ini
The url generator would sometimes give the wrong code or display the wrong accessory category.
CI: https://github.com/bdraco/HAP-python/actions/runs/522345020 (super error is fixed in https://github.com/ikalchev/HAP-python/pull/301)
Travis: https://travis-ci.org/github/ikalchev/HAP-python/builds/756787320
=> Fix pairing url generator

pyhap/accessory_driver.py, pyhap/hap_handler.py, pyhap/hap_protocol.py, tests/__init__.py, tests/conftest.py, tests/test_accessory.py, tests/test_accessory_driver.py, tests/test_camera.py, tests/test_characteristic.py, tests/test_encoder.py, tests/test_hap_handler.py, tests/test_hap_protocol.py, tests/test_loader.py, tests/test_service.py, tests/test_state.py, tox.ini
Pairing would sometimes fail because list pairings
was not implemented and an exception would be generated.
The state file could get corrupted if something went
wrong with the write. We now write a temp file and
move it in place after its fully written.
Ensure writing the state happens outside
of the event loop.
Also fixes connection stall on camera image failure.
Project test coverage up to 82.65% 
Fixes
```
2021-02-02 08:33:15 ERROR (MainThread) [pyhap.hap_handler] Failed to process request for: /pairings
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyhap/hap_handler.py", line 207, in dispatch
getattr(self, self.HANDLERS[self.command][path])()
File "/usr/local/lib/python3.8/site-packages/pyhap/hap_handler.py", line 608, in handle_pairings
raise …
```
=> Implement list pairings

pyhap/iid_manager.py
Avoids the linear search of objects to
find the iid. When there are a lot of
characteristics and accessories on a
bridge, the reconnect could cause the
bridge to go unavailable on slower systems (RPi3)
while it was re-subscribing to events.
We now use a dict lookup to find object
from the iid
=> Speed up new HAP event subscribe on new connections

pyhap/hap_handler.py, tests/test_hap_handler.py, tests/test_hap_protocol.py
Updated version of #306 pull request to work correctly with 3.2.0, add coverage, and timeout.
The handle_resource method from HAPServer class does not support situation when camera added to bridge and fails with Got a request for snapshot, but the Accessory does not define a "get_snapshot" method error. This is because it tries to check if bridge itself has the get_snapshot method.
This pull request fixes this problem.
=> Properly handle snapshots if camera added to bridge

pyhap/accessory_driver.py, pyhap/hap_handler.py, tests/test_accessory_driver.py, tests/test_hap_handler.py
Our current behavior is to send a `HTTPStatus.BAD_REQUEST` response when one of the setters generates an exception.  This causes the controller to drop the connection which can lead to the looping unavailable state for all homekit devices.
=> Implement partial success response for set_characteristics

pyhap/accessory_driver.py, pyhap/const.py, pyhap/hap_handler.py, tests/conftest.py, tests/test_accessory_driver.py, tests/test_hap_protocol.py
@ikalchev I thought I had solved this in #316 but it turns out it was the chunked encoding that seems to be the issue. Thanks for doing the 3.3.1 release as I wouldn't have been able to get the debug log that showed the problem since it was only apparent what was happening after a drop that #316 fixed. Sorry, but I think we need another release.
- Avoid sending chunked responses since iOS does not deal with it well
- Fix HTTP Status code strings
- Increase coverage
- Solve overflow on config version
=> Resolve unavailable condition on restart

pyhap/encoder.py, pyhap/util.py
We only support python 3.5 and later, remove legacy code
that was unreachable
=> Remove legacy python code

pyhap/accessory_driver.py, pyhap/hap_protocol.py, tests/test_accessory_driver.py, tests/test_hap_protocol.py
- Solves a memory leak with topics
- Increase test coverage
=> Cleanup subscriptions on client disconnect

pyhap/hap_handler.py, pyhap/hap_protocol.py, pyhap/hap_server.py, tests/test_accessory_driver.py, tests/test_hap_handler.py, tests/test_hap_protocol.py, tests/test_hap_server.py
- Increase the write buffer to ensure encrypted responses are written in one shot to avoid connection resets
- Ensure camera snapshots use content-length
- Remove unused timeout code
- Timeout idle connections after 90hrs
- Increase coverage
Should fix https://github.com/home-assistant/core/issues/47152
=> Resolve connection stability with large responses

.github/workflows/ci.yaml, pyhap/hap_handler.py, tests/test_hap_handler.py, tox.ini
The CI Fix is in https://github.com/ikalchev/HAP-python/pull/320 which needs to go in first
This one will need to be rebased as it will conflict with the other open PRs.
=> Add bandit to CI and address reported issues

pyhap/hap_protocol.py, tests/test_hap_protocol.py
- Improves handling of client closing connection cleanly
=> Complete hap_protocol coverage

pyhap/accessory_driver.py, pyhap/const.py, pyhap/hap_handler.py, tests/test_accessory_driver.py, tests/test_hap_handler.py
Previously we always sent a multi-status of 207 even when
there were no failures. HomeKit expects a HTTP 200 response
when there are no failures, and for status to be not
be set in the 100% success state.
This change **drastically** reduces the amount of polling that
the iOS device does because it no longer schedules a retry
based on the unexpected 207 which translates into a meaningful
improvement in battery life.
=> Ensure HTTP 200 status is sent when get_characteristics has no failures

pyhap/accessory_driver.py, pylintrc, pyproject.toml, setup.py, tests/conftest.py, tests/test_accessory.py, tests/test_accessory_driver.py, tests/test_hap_server.py
Creating an `AccessoryDriver` now accepts an `AsyncZeroconf` instance via `async_zeroconf_instance` instead of a `Zeroconf` instance via `zeroconf_instance`.  No changes are needed if a zeroconf instances was not being passed in.
=> Use zeroconf async registration functions

pyhap/accessory_driver.py
=> Remove watcher from Windows (they don't exist)

pyhap/accessory_driver.py, tests/test_accessory_driver.py
Some mDNS implementations were crashing when seeing the `SRV` records with a space which was translating to `HASS\032Bridge\032._hap._tcp.local.`
=> Handle additional cases of invalid hostnames

.github/workflows/ci.yaml, README.md
- 3.5 is EOL and since we need zeroconf 0.32.0+ which requires 3.6
we now require 3.6
=> Bump minimum python to 3.6

pyhap/encoder.py, pyhap/hap_handler.py, pyhap/state.py, requirements.txt, requirements_all.txt, setup.py, tests/test_accessory_driver.py, tests/test_encoder.py, tests/test_state.py
- The ed25519 package is no longer recommended by the maintainer https://github.com/warner/python-ed25519#not-recommended-for-new-applications-use-pynacl-instead
- Since we are already using cryptography, it makes sense to use that instead of pynacl
- In testing this was ~2.8x faster which speeds up the transition from cellular to wifi when coming home
=> Switch to using cryptography ed25519 

.github/workflows/ci.yaml, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/hap_protocol.py, pyhap/hap_server.py, tests/conftest.py, tests/test_accessory.py, tests/test_accessory_driver.py, tests/test_characteristic.py, tests/test_hap_server.py
- Only send an event if the characteristic has changed value
- Coalesce events that happen within the same 500ms window except
for Button Events and Programmable Switch Events which are delivered
as soon as possible
- Ensure Programmable Switch Events always serialize to null
to handle the special case in the spec (except for events).
- MAJOR: Sending an event after the client has been unsubscribed may cause
iOS to disconnect the accessory and reconnect which makes everything
go unavailable while the connection is set back up. We now check to
make sure that the client still wants the event right before sending it
to avoid the disconnect.
Fixes #359 Fixes #364
=> Reduce event overhead

pyhap/characteristic.py, tests/test_characteristic.py
- Solves `XX.0` unexpectedly appearing in events and get chars
=> Ensure floating point values are truncated for int formats

.github/workflows/ci.yaml, pyhap/hap_handler.py, pyhap/hap_protocol.py, tests/test_hap_protocol.py
- iOS will terminate the connection if it does not respond within
10 seconds, so we only allow 9 seconds to avoid this.
- We no longer need to pause reading when taking a snapshot
as we have a working timeout
=> Decrease snapshot timeout to avoid being disconnected

.github/workflows/ci.yaml, pyhap/hap_protocol.py, tests/test_hap_protocol.py
- If the remote end closed the connection, we would still try to write
the camera snapshot if it came back after the connection was closed.
=> Avoid writing delayed camera snapshots when the connection is closed

pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/const.py, tests/test_accessory.py, tests/test_accessory_driver.py, tests/test_hap_handler.py
=> Protocol 1.1: Upgrade protocol version (HAP-python 4.0.0)

pyhap/accessory.py, pyhap/accessory_driver.py, tests/test_accessory_driver.py
- Some accessories need to know about changes to linked
services since one can affect the other. This is
similar to service callbacks, but at one level
higher to resolve conflicts such as https://github.com/home-assistant/core/issues/50824#issuecomment-893844559
=> Implement accessory level callbacks

pyhap/accessory_driver.py, pyhap/const.py, pyhap/encoder.py, pyhap/loader.py, pyhap/state.py, pyhap/util.py, tests/test_accessory_driver.py, tests/test_state.py
- We now hash a sorted version of `/accessories` at start
so we can tell when it changes and increment the config version
- Incrementing the config version tells iOS that it needs to
evict its cache of /accessories to prevent invalid state
- Fixes accessories showing non-responsive or missing services
because their services have changed and iOS is unaware because its
using the old version of `/accessories`
=> Increment the config version when the accessories change

pyhap/characteristic.py, tests/test_characteristic.py
- Ensure strings are never longer than the current value of
maxLen. Previously we would increase maxLen when it was too
short, but since the iOS device will not see the maxLen change
until the config version has been incremented, this would result
in it seeing it as an invalid value and disconnect
- Ensure any set numeric value observes minStep. If minStep was 2, it
was possible to set a value that was invalid and cause a disconnect
=> Handle additional cases of invalid values

pyhap/accessory_driver.py, tests/test_accessory_driver.py
- When there are multiple bridges running with the same address, each
A record has to be kept fresh. By using the same server for all the bridges
we avoid a case where the amount of broadcast traffic exceeds the limit
and the bridges become unavailable
=> Allow passing the zeroconf server name when creating the AccessoryDriver

setup.py
- Fixes a case where a HomeKit bridge can take a while to update
because it is waiting to see if an AAAA (IPv6) address is available
- Changes: https://github.com/jstasiak/python-zeroconf/compare/0.32.0...0.36.2
=> Bump zeroconf to 0.36.2

pyhap/characteristic.py, tests/test_characteristic.py
As of iOS 15.1, Siri requests TargetHeatingCoolingState
as Auto reguardless if its a valid value or not.
Consumers of this api may wish to set allow_invalid_client_values
to True and handle converting the Auto state to Cool or Heat
depending on the device.
Reference: https://github.com/home-assistant/core/issues/60203
=> Allow invalid client values when enabled

pyhap/hap_handler.py, tests/test_hap_handler.py
Noticed that this happens twice while debugging so I figured I'd optimize it
=> Avoid parsing the url twice

.github/workflows/ci.yaml, docs/source/conf.py, pyhap/accessory.py, pyhap/camera.py, pyhap/hap_crypto.py, pyhap/hap_handler.py, pyhap/hap_protocol.py, pylintrc, setup.py, tests/conftest.py, tests/test_characteristic.py, tests/test_hap_protocol.py, tests/test_service.py
The ChaCha20Poly1305 that comes with cryptography recreates the
ctx every time encrypt is called.  Since we call encrypt in
a loop, we can avoid this overhead by using ChaCha20Poly1305Reusable
instead as we are doing everything in the same thread.
This makes quite a difference for latency of large payloads such as camera images. It also seems to fix the Home app stalling out on iOS 16 betas when using them with Home Assistant's HomeKit integration.
=> Switch to using ChaCha20Poly1305Reusable for encryption

pyhap/accessory.py, pyhap/camera.py, pyhap/characteristic.py, pyhap/iid_manager.py, pyhap/service.py, pyhap/util.py, tests/test_accessory.py, tests/test_camera.py, tests/test_characteristic.py, tests/test_service.py
Currently we rely on creation order to keep iids the same but this is not reliable since services and chars can change. To solve this we need a custom iid manager that tracks iid between restarts to ensure that iids remain stable for the lifetime of the accessory.
Needed to fix (only a small part) https://github.com/home-assistant/core/issues/78092 via https://github.com/home-assistant/core/pull/79913
=> Add support for a custom iid manager

.gitignore, adaptive_lightbulb.py, pyhap/resources/characteristics.json, pyhap/resources/services.json
Add necessary characteristics to enable implementation of Adaptive Lightning. Also provide a demo light bulb implementation to demonstrate the basic usage of the newly added characteristics.
This PR closes #284
=> Add necessary support for Adaptive Lightning

pyhap/accessory_driver.py, pyhap/state.py, pyhap/util.py, tests/conftest.py, tests/test_accessory_driver.py, tests/test_camera.py, tests/test_characteristic.py, tests/test_hsrp.py, tests/test_state.py, tox.ini
needed for ipv6 support / dual stack https://github.com/home-assistant/core/pull/94126
=> Allow passing multiple ip to advertise on to AccessoryDriver

docs/source/conf.py
This PR adds a `source` button to each function/class signature on the docs website. People can directly view the code on the docs website without switching to the repository, making source code viewing easier.
=> Add source button to docs

pyhap/accessory_driver.py, pyhap/encoder.py, pyhap/hap_handler.py, pyhap/state.py, tests/test_encoder.py, tests/test_hap_handler.py, tests/test_state.py, tox.ini
apple seems to keep changing the case on these so we will now keep the binary blob and send back the exact bytes that was used in pairing when the client list pairings.
This should fix the users having trouble after migrating to the new home arch
=> Retain the original format of the UUID

pyhap/hap_crypto.py
Every loop would generate a multiple new bytes strings which was quite expensive (more than the encryption itself)
By joining them all together at the end we only have to do it once
=> Improve encryption performance

pyhap/resources/characteristics.json, pyhap/resources/services.json
This pull request adds following services and characteristics into the `characteristics.json` and `services.json` files:
- AccessoryInformation (Existing):
* HardwareFinish:   used to retrieve hardware finish (color, material) in order to draw home key pass in a matching color.
- NFCAccess:
* ConfigurationState
* NFCAccessSupportedConfiguration: used to retrieve amount of keys that a lock can store.
* NFCAccessControlPoint: used to configure keys: write/read/delete device/reader keys, etc.
Information about those services had been taken from:
- [@KhaosT - HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS/commit/80cdb1535f5bee874cc06657ef283ee91f258815);
- [@kupa22 - Apple Home Key](https://github.com/kupa22/apple-homekey)
=> Add services and characteristics used by Home Keys

pyhap/hap_handler.py, tests/test_hap_handler.py
We didn't used to save the raw bytes, but on the success case, iOS is going to send them to us again so we can save them if they are missing
Fixes #455
=> Save raw client username bytes if they are missing on successful pair verify

pyhap/accessory_driver.py, tests/test_accessory_driver.py
This commit aims at refactoring set_characteristics method, particularly by doing the following
1. Unwrapping multi-layer nested loops into comprehensions and/or single layer loops where possible.
2. Removing as much (if/else) branching as possible
3. Removing (dict) mutations and redundant variables where possible
4. Trying to separate discrete operations into separate loops (for notifications, query setters, accessory + service callbacks)
Some of the changes to the code required modifying 2 tests created by me for write responses, as new behaviour makes it so that no write response value is returned if it wasn't requested, even if callback returned one. This is actually better than before, because this way if someone's legacy code returns a value from a setter by accident, it won't be …
=> Refactor set_characteristics

.coveragerc, pyhap/accessory.py, pyhap/accessory_driver.py, pyhap/characteristic.py, pyhap/hap_crypto.py, pyhap/hap_handler.py, pyhap/service.py, pyhap/util.py, tests/test_service.py
will conflict with https://github.com/ikalchev/HAP-python/pull/462 so it should merge first
=> Add some more typing characteristics and services

pyhap/hap_event.py, pyhap/hap_handler.py, pyhap/hap_protocol.py
~~needs https://github.com/ikalchev/HAP-python/pull/463 first~~
- Add some typing
- Avoid some bytes concat
=> Small cleanups to the protocol handler

pyhap/accessory.py, pyhap/hap_protocol.py, pyhap/hap_server.py, tests/test_hap_protocol.py
The check for next_event was not correct for explict closes as https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_connection.py#L445
will only return h11.ConnectionClosed as an object and not a type
=> Fix handling of explict close

pyhap/__init__.py, pyhap/accessory.py
Some tests run locally for `home-assistant/core` would fail with a cryptic "base36 is not defined" error if that library was not installed.
This PR:
* makes that error message cleaner – it's now a `RuntimeError` that has the import error as a reason
* makes `pyhap` not import `base36` or `QRCode` at all until they are needed 
* in doing that removes the `SUPPORT_QR_CODE` flag; based on [GitHub Code Search](https://github.com/search?q=SUPPORT_QR_CODE+language%3APython&type=code&l=Python) there are no external users for that flag that I can see.
=> Late-import base36 and QR code libraries; remove SUPPORT_QR_CODE flag

pyhap/hap_crypto.py, pyhap/hap_protocol.py, tests/test_hap_crypto.py, tests/test_hap_protocol.py
With Python 3.12+ and later `transport.writelines` is implemented as [`sendmsg(..., IOV_MAX)`](https://github.com/python/cpython/issues/91166) which allows us to avoid joining the bytes and sending them in one go.
Older Python will effectively do the same thing we do now `b"".join(...)`
=> Implement zerocopy writes for the encrypted protocol

pyhap/__init__.py, pyhap/accessory.py
Reverts ikalchev/HAP-python#470
This change introduced blocking I/O in the event loop to load python code
This also broke the tests
`AttributeError: <module 'pyhap.accessory' from '/home/runner/work/HAP-python/HAP-python/pyhap/accessory.py'> does not have the attribute 'SUPPORT_QR_CODE'`
=> Revert "Late-import base36 and QR code libraries; remove SUPPORT_QR_CODE flag"

pyhap/accessory_driver.py
On Windows, os.chmod fails if the target file doesn't exist.  Avoid calling it in that case.
=> Avoid os.chmod failing on Windows if file non-existant
